# Generated by Django 4.0.1 on 2022-01-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.CharField(choices=[('TEC', 'Tecnologia'), ('GR', 'Geral'), ('OT', 'Outros')], default='GR', max_length=3),
        ),
    ]
