# Generated by Django 4.0.1 on 2022-01-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_posts_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='aproved',
            field=models.BigIntegerField(default=True),
        ),
    ]
