# Generated by Django 4.0.1 on 2022-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_posts_aproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='aproved',
        ),
        migrations.AddField(
            model_name='posts',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
