# Generated by Django 4.0.1 on 2022-01-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_posts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='imagem',
        ),
    ]
